SELECT
	A.ID_BANCO
	,B.NOMBRE BANCO
	,A.ID_PRODUCTO
	,C.NOMBRE PRODUCTO
	,A.STATUS
FROM
	EAI_ADM_CLIENTES_BANCOS A
	,EAI_CAT_BANCOS B
	,EAI_CAT_PRODUCTOS C
WHERE A.ID_CLIENTE = {0}
	AND A.ID_BANCO = B.ID_BANCO
	AND A.ID_PRODUCTO = C.ID_PRODUCTO
ORDER BY B.NOMBRE, C.NOMBRE