SELECT
	A.ID_STATUS
	,B.DESCRIPCION
	,A.ID_FASE
	,C.DESCRIPCION FASE
FROM
	EAI_ADM_CLIENTES_STATUS A
	,EAI_CAT_STATUS B
	,EAI_CAT_FASES C
WHERE A.ID_CLIENTE = {0}
	AND A.ID_STATUS = B.ID_STATUS
	AND A.ID_FASE = C.ID_FASE
ORDER BY A.FECHA_CREACION